---
- name: Download VSCode
  ansible.builtin.get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64"
    dest: "/tmp/vscode.deb"
    mode: "0770"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Apt Install VSCode
  become: true
  become_user: root

  ansible.builtin.apt:
    deb: "/tmp/vscode.deb"
